language: cpp

os:
  - linux
  - osx
  - windows

addons:
  # Install dependencies for Linux
  apt:
    packages:
      - libxrandr-dev
      - libxinerama-dev
      - libx11-dev
      - libxcursor-dev
      - libxi-dev
      - libgl1-mesa-dev
      - doxygen
  # Install dependencies for MacOS
  homebrew:
    packages:
      - doxygen

before_script:
  - mkdir build
  - cd build
  - CMAKE_FLAGS=""
  - |-
      case $TRAVIS_OS_NAME in
        windows)
          CMAKE_FLAGS="${CMAKE_FLAGS} -D BUILD_DOCUMENTATION=OFF"
          ;;
      esac
  - cmake .. ${CMAKE_FLAGS}

script:
  - cmake --build .

