language: cpp

os:
  - linux
  - osx

addons:
  # Install dependencies for Linux
  apt:
    packages:
      - libxrandr-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

