language: cpp

os:
  - linux
  - osx

addons:
  # Install dependencies for Linux
  apt:
    packages:
      - libxrandr-dev
      - libxinerama-dev
      - libx11-dev
      - libxcursor-dev
      - libxi-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

